config/routes.rb
Rails.application.routes.draw do
  get 'pages/envio'
  get 'pages/recibo'
  post 'pages/save_result'
  root 'pages#envio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def envio
  end

  def save_result
    @result = Result.create!(number1: params[:a], number2: params[:b])
    redirect_to pages_recibo_path(id: @result.id)
  end

  def recibo
    # a = params[:a].to_i
    # b = params[:b].to_i
    # @suma = a + b

    @result = Result.find(params[:id])
    @suma = @result.number1 + @result.number2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejemplo01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/envio.html.erb
<h3>Formulario:</h3>

<p>Ingrese 2 números para sumar:</p>
<%= form_tag(pages_save_result_path, method: :post) do %>
  <%= number_field_tag 'a' %>
  <%= number_field_tag 'b' %>
  <%= submit_tag 'Enviar' %>
<% end %>

<!--
<p>Ingrese 2 números para sumar:</p>
<form action="<%= pages_save_result_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
  <input type="text" name="a">
  <input type="text" name="b">
  <input type="submit" value="enviar">
</form>
-->

app/views/pages/recibo.html.erb
<h3>La suma es:</h3>

<%= @suma %>